name: screen_observer
description: Similar to RouteObserver, but watch for screen transitions instead of route
version: 1.0.0
repository: https://github.com/Danopie/screen_observer

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
